# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.3'

# Define services
services:

  mongodb:
    container_name: mongo-db-sunesis-demo-api
    image: 'mongo:4.2.10-bionic'
    hostname: mongodb
    command: mongod --port 27018
    ports:
      - "27018:27018"
    networks:
      - backend

  app-server:
    container_name: sunesis-demo-api
    image: demoapi:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    restart: on-failure
    depends_on:
      - mongodb
    links:
      - mongodb:mongodbhost
    networks:
      - backend

networks:
  backend:
